/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personelyönetimi;


import javax.swing.JOptionPane;

import personelyönetimi.pesoneltablosu;

/**
 *
 * @author pc
 */
public class personelYönetimEkranı extends javax.swing.JFrame {
    
    personelİşlemler islemler =  new personelİşlemler();
    /**
     * Creates new form personelYönetimEkranı
     */
    public personelYönetimEkranı() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        personelParola = new javax.swing.JTextField();
        personelİsim = new javax.swing.JTextField();
        personelTel = new javax.swing.JTextField();
        Maaş = new javax.swing.JTextField();
        Ekle = new javax.swing.JButton();
        Sil = new javax.swing.JButton();
        Düzenle = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        personelgöster = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Cinsiyet = new javax.swing.JComboBox<>();
        personelId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));
        jPanel1.setForeground(new java.awt.Color(102, 0, 51));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERSONEL YÖNETİM EKRANI");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personel ID :");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parola");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ad ve Soyad");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefon Numarası");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Maaş");

        personelParola.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        personelİsim.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        personelTel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Maaş.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Ekle.setBackground(new java.awt.Color(102, 102, 102));
        Ekle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Ekle.setForeground(new java.awt.Color(102, 0, 51));
        Ekle.setText("EKLE");
        Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleActionPerformed(evt);
            }
        });

        Sil.setBackground(new java.awt.Color(102, 102, 102));
        Sil.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sil.setForeground(new java.awt.Color(102, 0, 51));
        Sil.setText("SİL");
        Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilActionPerformed(evt);
            }
        });

        Düzenle.setBackground(new java.awt.Color(102, 102, 102));
        Düzenle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Düzenle.setForeground(new java.awt.Color(102, 0, 51));
        Düzenle.setText("DÜZENLE");
        Düzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DüzenleActionPerformed(evt);
            }
        });

        Temizle.setBackground(new java.awt.Color(102, 102, 102));
        Temizle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Temizle.setForeground(new java.awt.Color(102, 0, 51));
        Temizle.setText("TEMİZLE");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        personelgöster.setBackground(new java.awt.Color(102, 102, 102));
        personelgöster.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personelgöster.setForeground(new java.awt.Color(102, 0, 51));
        personelgöster.setText("PERSONELLERİ GÖSTER");
        personelgöster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelgösterActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cinsiyet");

        Cinsiyet.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cinsiyet.setForeground(new java.awt.Color(102, 0, 51));
        Cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERKEK", "KADIN" }));
        Cinsiyet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cinsiyet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CinsiyetİtemStateChanged(evt);
            }
        });

        personelId.setBackground(new java.awt.Color(255, 255, 255));
        personelId.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        personelId.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ÇELIK OTEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Maaş, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(personelİsim)
                                    .addComponent(personelParola, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(personelTel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(Cinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personelId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(personelgöster, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(Düzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(109, 109, 109))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personelId))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(personelİsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(personelParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personelTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Maaş, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(personelgöster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temizle)
                    .addComponent(Düzenle)
                    .addComponent(Sil)
                    .addComponent(Ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleActionPerformed
        // TODO add your handling code here:
        if((personelİsim.getText().isEmpty())||(personelParola.getText().isEmpty())||(personelTel.getText().isEmpty())||(Maaş.getText().isEmpty())){
            
            JOptionPane.showMessageDialog(this,"Kayıt İşlemi Başarısız...");
        
        }else{
        
        String ad  =  personelİsim.getText();
        String parola = personelParola.getText();
        String telno =personelTel.getText();
        String maaş=Maaş.getText();
        String cinsiyet =Cinsiyet.getSelectedItem().toString();

        islemler.personelEkle(ad,parola,telno,maaş,cinsiyet);
        
        

        

        JOptionPane.showMessageDialog(this,"Yeni Müşteri Başarıyla Eklendi...");
        personelId.setText("");
        personelİsim.setText("");
        personelParola.setText("");
        personelTel.setText("");
        Maaş.setText("");
        }
    }//GEN-LAST:event_EkleActionPerformed

    private void SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilActionPerformed
        // TODO add your handling code here:
        
            if(!personelId.getText().isEmpty()){
                int id = Integer.valueOf(personelId.getText());
                islemler.personelSil(id);
                JOptionPane.showMessageDialog(this,"Personel başarıyla silindi...");
                personelId.setText("");
                personelİsim.setText("");
                personelParola.setText("");
                personelTel.setText("");
                Maaş.setText("");
                
            }else if(personelId.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Id doldurunuz."); 
            }
            else{
                JOptionPane.showMessageDialog(this,"Geçerli Bir Id giriniz.");
            }
            

            

            

            

        
    }//GEN-LAST:event_SilActionPerformed

    private void DüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DüzenleActionPerformed
        // TODO add your handling code here:
        
        String ad  =  personelİsim.getText();
        String parola= personelParola.getText();
        String telno = personelTel.getText();
        String maaş= Maaş.getText();
        String cinsiyet=Cinsiyet.getSelectedItem().toString();
        
        
        

        
            if(!personelId.getText().isEmpty()){
                int id;
                id = Integer.valueOf(personelId.getText());
                
                islemler.personelGuncelle(id,ad,parola,telno,maaş,cinsiyet);
                JOptionPane.showMessageDialog(this,"Personel başarıyla güncellendi...");
                personelId.setText("");
                personelİsim.setText("");
                personelParola.setText("");
                personelTel.setText("");
                Maaş.setText("");
                //pesoneltablosu.personelGoruntule();
            }
            else if(personelId.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Id doldurunuz."); 
            }
            else{
                JOptionPane.showMessageDialog(this,"Geçerli Bir Id giriniz.");
            }
            
           

            

            
        
    }//GEN-LAST:event_DüzenleActionPerformed

    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
        // TODO add your handling code here:
        personelId.setText("");
        personelİsim.setText("");
        personelParola.setText("");
        personelTel.setText("");
        Maaş.setText("");
        

    }//GEN-LAST:event_TemizleActionPerformed

    private void personelgösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelgösterActionPerformed
        // TODO add your handling code here:
        new pesoneltablosu().setVisible(true);
    }//GEN-LAST:event_personelgösterActionPerformed

    private void CinsiyetİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CinsiyetİtemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_CinsiyetİtemStateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelYönetimEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Cinsiyet;
    private javax.swing.JButton Düzenle;
    private javax.swing.JButton Ekle;
    public static javax.swing.JTextField Maaş;
    private javax.swing.JButton Sil;
    private javax.swing.JButton Temizle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel personelId;
    public static javax.swing.JTextField personelParola;
    public static javax.swing.JTextField personelTel;
    private javax.swing.JButton personelgöster;
    public static javax.swing.JTextField personelİsim;
    // End of variables declaration//GEN-END:variables

    
}
