/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OdaYönetimi;



import javax.swing.JOptionPane;




/**
 *
 * @author pc
 */
public class odaYönetimEkranı extends javax.swing.JFrame {
    
    odaİşlemler islemler =  new odaİşlemler();
    
    /**
     * Creates new form odaYönetimEkranı
     */
    public odaYönetimEkranı() {
        initComponents();
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        odaNumara = new javax.swing.JTextField();
        telefonNo = new javax.swing.JTextField();
        odaTürü = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Ekle = new javax.swing.JButton();
        Sil = new javax.swing.JButton();
        Düzenle = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        OdaTipi = new javax.swing.JButton();
        rezerve = new javax.swing.JComboBox<>();
        personelgöster = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));
        jPanel1.setForeground(new java.awt.Color(102, 0, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Oda Tipi");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefon No");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rezerve mi? ");

        odaNumara.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        telefonNo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        odaTürü.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ODA YÖNETİMİ");

        Ekle.setBackground(new java.awt.Color(102, 102, 102));
        Ekle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Ekle.setForeground(new java.awt.Color(102, 0, 51));
        Ekle.setText("EKLE");
        Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleActionPerformed(evt);
            }
        });

        Sil.setBackground(new java.awt.Color(102, 102, 102));
        Sil.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Sil.setForeground(new java.awt.Color(102, 0, 51));
        Sil.setText("SİL");
        Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilActionPerformed(evt);
            }
        });

        Düzenle.setBackground(new java.awt.Color(102, 102, 102));
        Düzenle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Düzenle.setForeground(new java.awt.Color(102, 0, 51));
        Düzenle.setText("DÜZENLE");
        Düzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DüzenleActionPerformed(evt);
            }
        });

        Temizle.setBackground(new java.awt.Color(102, 102, 102));
        Temizle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Temizle.setForeground(new java.awt.Color(102, 0, 51));
        Temizle.setText("TEMİZLE");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        OdaTipi.setBackground(new java.awt.Color(102, 102, 102));
        OdaTipi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        OdaTipi.setForeground(new java.awt.Color(102, 0, 51));
        OdaTipi.setText("Oda Tipi Göster");
        OdaTipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdaTipiActionPerformed(evt);
            }
        });

        rezerve.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rezerve.setForeground(new java.awt.Color(102, 0, 51));
        rezerve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EVET", "HAYIR" }));
        rezerve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rezerve.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rezerveİtemStateChanged(evt);
            }
        });

        personelgöster.setBackground(new java.awt.Color(102, 102, 102));
        personelgöster.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personelgöster.setForeground(new java.awt.Color(102, 0, 51));
        personelgöster.setText("ODALARI GÖSTER");
        personelgöster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelgösterActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numara");

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ÇELIK OTEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(personelgöster, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rezerve, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(odaTürü, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OdaTipi))
                            .addComponent(odaNumara, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Düzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel10)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(odaNumara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odaTürü, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(OdaTipi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rezerve, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(personelgöster)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Düzenle)
                            .addComponent(Temizle)
                            .addComponent(Sil)
                            .addComponent(Ekle))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleActionPerformed
        // TODO add your handling code here:
        if((odaNumara.getText().isEmpty())||(odaTürü.getText().isEmpty())||(telefonNo.getText().isEmpty())){
            
            JOptionPane.showMessageDialog(this,"Kayıt İşlemi Başarısız...");
        
        }else{
        
        String numara  =  odaNumara.getText();
       
        String türü = odaTürü.getText();
        String telno =telefonNo.getText();
        
        String rezervemi =rezerve.getSelectedItem().toString();

        islemler.odaEkle(numara,türü,telno,rezervemi);

        

        JOptionPane.showMessageDialog(this,"Yeni oda Başarıyla Eklendi...");
        }
    }//GEN-LAST:event_EkleActionPerformed

    private void SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilActionPerformed
        // TODO add your handling code here:
        if(!ID.getText().isEmpty()){
            int id = Integer.valueOf(ID.getText());
            islemler.odaSil(id);
            JOptionPane.showMessageDialog(this,"Oda başarıyla silindi...");
            ID.setText("");
            odaNumara.setText("");
            odaTürü.setText("");
            telefonNo.setText("");
                
                
                
        }else{
            JOptionPane.showMessageDialog(this,"Eksik Bilgi."); 
        }
            
            
    }//GEN-LAST:event_SilActionPerformed

    private void DüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DüzenleActionPerformed
        // TODO add your handling code here:
        
        String numara=odaNumara.getText();
        String tipi = odaTürü.getText();
        String telno =telefonNo.getText();
        String rezervemi=rezerve.getSelectedItem().toString();
        
        
        
        if(ID.getText().isEmpty()||odaNumara.getText().isEmpty()||odaTürü.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Eksik Bilgi...");         
                
                
        }else {
            
            int id = Integer.valueOf(ID.getText());
            islemler.odaGuncelle(id,numara,tipi,telno,rezervemi);
            JOptionPane.showMessageDialog(this,"Oda başarıyla güncellendi...");
            ID.setText("");
            odaNumara.setText("");
            odaTürü.setText("");
            telefonNo.setText("");
        }
            
        
        
        

        
        
            
    }//GEN-LAST:event_DüzenleActionPerformed

    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
        // TODO add your handling code here:
        ID.setText("");
        odaNumara.setText("");
        odaTürü.setText("");
        telefonNo.setText("");
        
    }//GEN-LAST:event_TemizleActionPerformed

    
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void OdaTipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdaTipiActionPerformed
        // TODO add your handling code here:
        new odaTipi().setVisible(true);
        
    }//GEN-LAST:event_OdaTipiActionPerformed

    private void rezerveİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rezerveİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rezerveİtemStateChanged

    private void personelgösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelgösterActionPerformed
        // TODO add your handling code here:
        new odatablosu().setVisible(true);
    }//GEN-LAST:event_personelgösterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odaYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odaYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odaYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odaYönetimEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odaYönetimEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Düzenle;
    private javax.swing.JButton Ekle;
    public static javax.swing.JLabel ID;
    private javax.swing.JButton OdaTipi;
    private javax.swing.JButton Sil;
    private javax.swing.JButton Temizle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField odaNumara;
    public static javax.swing.JTextField odaTürü;
    private javax.swing.JButton personelgöster;
    public static javax.swing.JComboBox<String> rezerve;
    public static javax.swing.JTextField telefonNo;
    // End of variables declaration//GEN-END:variables
}
