/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AnaEkranlar;

import AdminYönetimi.adminEkranı;
import MüşteriYönetimi.müşteriYönetimEkranı;
import OdaYönetimi.odaYönetimEkranı;
import personelyönetimi.personelYönetimEkranı;



/**
 *
 * @author pc
 */
public class AdminAnaEkranı extends javax.swing.JFrame {

    /**
     * Creates new form AdminAnaEkranı
     */
    public AdminAnaEkranı() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        geriTuşu3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        adminYönetimi = new javax.swing.JButton();
        personelYönetimi = new javax.swing.JButton();
        personelYönetimi1 = new javax.swing.JButton();
        personelYönetimi2 = new javax.swing.JButton();
        karşılamaAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("ADMİN ANA EKRANI");

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 51));
        jLabel18.setText("x");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ÇELIK OTEL");

        geriTuşu3.setBackground(new java.awt.Color(255, 255, 255));
        geriTuşu3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        geriTuşu3.setForeground(new java.awt.Color(102, 0, 51));
        geriTuşu3.setText("<");
        geriTuşu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geriTuşu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriTuşuMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Corbel Light", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 51));
        jLabel20.setText("software developer Alihan");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminYönetimi.setBackground(new java.awt.Color(102, 102, 102));
        adminYönetimi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        adminYönetimi.setForeground(new java.awt.Color(102, 0, 51));
        adminYönetimi.setText("Admin Yönetimi");
        adminYönetimi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminYönetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminYönetimiActionPerformed(evt);
            }
        });

        personelYönetimi.setBackground(new java.awt.Color(102, 102, 102));
        personelYönetimi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personelYönetimi.setForeground(new java.awt.Color(102, 0, 51));
        personelYönetimi.setText("Personel Yönetimi");
        personelYönetimi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personelYönetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelYönetimiActionPerformed(evt);
            }
        });

        personelYönetimi1.setBackground(new java.awt.Color(102, 102, 102));
        personelYönetimi1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personelYönetimi1.setForeground(new java.awt.Color(102, 0, 51));
        personelYönetimi1.setText("Oda Yönetimi");
        personelYönetimi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personelYönetimi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelYönetimi1ActionPerformed(evt);
            }
        });

        personelYönetimi2.setBackground(new java.awt.Color(102, 102, 102));
        personelYönetimi2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personelYönetimi2.setForeground(new java.awt.Color(102, 0, 51));
        personelYönetimi2.setText("Müşteri Yönetimi");
        personelYönetimi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personelYönetimi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelYönetimi2ActionPerformed(evt);
            }
        });

        karşılamaAdmin.setBackground(new java.awt.Color(255, 255, 255));
        karşılamaAdmin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        karşılamaAdmin.setForeground(new java.awt.Color(102, 0, 51));
        karşılamaAdmin.setText("Hoşgeldiniz ....");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(geriTuşu3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(238, 238, 238)))
                        .addComponent(jLabel18)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(328, 328, 328))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(personelYönetimi2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelYönetimi1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelYönetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminYönetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(karşılamaAdmin)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(geriTuşu3)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addGap(33, 33, 33)
                .addComponent(karşılamaAdmin)
                .addGap(35, 35, 35)
                .addComponent(adminYönetimi)
                .addGap(18, 18, 18)
                .addComponent(personelYönetimi)
                .addGap(18, 18, 18)
                .addComponent(personelYönetimi1)
                .addGap(18, 18, 18)
                .addComponent(personelYönetimi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void geriTuşuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriTuşuMouseClicked
        // TODO add your handling code here:
        new giriş().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_geriTuşuMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void adminYönetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminYönetimiActionPerformed
        // TODO add your handling code here:
        new adminEkranı().setVisible(true);
    }//GEN-LAST:event_adminYönetimiActionPerformed

    private void personelYönetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelYönetimiActionPerformed
        // TODO add your handling code here:
        new personelYönetimEkranı().setVisible(true);
    }//GEN-LAST:event_personelYönetimiActionPerformed

    private void personelYönetimi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelYönetimi1ActionPerformed
        // TODO add your handling code here:
        new odaYönetimEkranı().setVisible(true);
    }//GEN-LAST:event_personelYönetimi1ActionPerformed

    private void personelYönetimi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelYönetimi2ActionPerformed
        // TODO add your handling code here:
        new müşteriYönetimEkranı().setVisible(true);
    }//GEN-LAST:event_personelYönetimi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAnaEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAnaEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAnaEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAnaEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAnaEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminYönetimi;
    public static javax.swing.JLabel geriTuşu3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JLabel karşılamaAdmin;
    private javax.swing.JButton personelYönetimi;
    private javax.swing.JButton personelYönetimi1;
    private javax.swing.JButton personelYönetimi2;
    // End of variables declaration//GEN-END:variables

    
}
